// This file was generated by RedwoodJS
import { Success } from './PropertiesCell'
import type { CellProps } from '@redwoodjs/web'
import type { PropertiesQuery, PropertiesQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './PropertiesCell'

type CellInputs = CellProps<SuccessType, PropertiesQuery, PropertiesQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
