// This file was generated by RedwoodJS
import { Success } from './ListingCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindListingById, FindListingByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './ListingCell'

type CellInputs = CellProps<SuccessType, FindListingById, FindListingByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
