// This file was generated by RedwoodJS
import { Success } from './EditListingCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditListingById, EditListingByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditListingCell'

type CellInputs = CellProps<SuccessType, EditListingById, EditListingByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
