// This file was generated by RedwoodJS
import { Success } from './ListingsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindListings, FindListingsVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './ListingsCell'

type CellInputs = CellProps<SuccessType, FindListings, FindListingsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
