// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
}
