// This file was generated by RedwoodJS
import AboutPageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/AboutPage/AboutPage'
import FatalErrorPageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/NotFoundPage/NotFoundPage'
import TeamPageType from '/Users/coder/repos/arunabhdas/githubrepos/offside-ai/offside-ai/web/src/pages/TeamPage/TeamPage'

declare global {
  const AboutPage: typeof AboutPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const TeamPage: typeof TeamPageType
}
